server:
  port: 55010
spring:
  application:
    name: xa-business
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xa_business
    username: root
    password: 123456
# seata client
seata:
  tx-service-group: my-xa-tx-group
  service:
    vgroup-mapping:
      my-xa-tx-group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP